deploy:
  provider: gae
  keyfile: client_secret.json
  project: gae-circleci-integration
  version: "travis"
  skip_cleanup: true
  # default: true

before_install:
- openssl aes-256-cbc -K $encrypted_c3f179556918_key -iv $encrypted_c3f179556918_iv
  -in client_secret.json.enc -out client_secret.json -d
